Added example markdown for knit2synapse functionalities
Sage-Bionetworks/knit2synapse pull request #18
Opened 2018-06-14 20:10 UTC by th1vairam

Looking at the recent inflow of new users, here are some sample markdown examples for them to use.

2018-06-14 20:13 UTC, kdaily requested changes
needs to go into a vignettes directory. See http://r-pkgs.had.co.nz/vignettes.html

2018-06-14 20:13 UTC, kdaily commented on examples/example_createAndKnitToFileEntity.Rmd
> +## R Markdown
remove this boiler plate section

2018-06-14 20:13 UTC, kdaily commented on examples/example_createAndKnitToFileEntity.Rmd
> +title: "Create a synapse file entity, push the R markdown as file entity to synapse, and populate the synapse wiki with results"
shorter title

2024-12-03 21:25 UTC, jaclynbeck-sage commented
Merging with a new branch `vignette_updates` so I can address the comments before merging with master.

2024-12-03 21:25 UTC, merged